# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
import('Test')
import('Sonar')

default_platform(:ios)

platform :ios do

    lane :build do
        build_app(
            scheme: "ExampleLaneiOS"
            )
    end

    lane :pr_merge_on_develop do
        sonar_analysis
        build
        run_unit_tests
        run_ui_tests
    end


end
